version:  2.1
jobs:
    # deploy: EC2 に SSH 接続して、デプロイを実行する
    deploy: 
        docker:
            - image: cystdot/ubuntu:ToExecSsh #imageの中に秘密鍵入ってるからだめ
              auth:
                username: ${DOCKER_USER}
                password: ${DOCKER_PASSWORD}
        steps:
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh -i /.ssh/aws-network-test-key-latest.pem ${SSH_USER}@${SSH_HOST} 'sh deploy-me.sh'

    test:
        docker:
            - image: cystdot/circleci:totest
        steps:
            - run: pwd
            - run: ls
            - run: cd spring-demo-gradle
            - run: pwd
            - run: gradle test
            - run: echo "unko"

workflows:
    version: 2
    # test_and_deploy ジョブ: 一番最初に呼ばれるジョブ
    test_and_deploy:
        # test ジョブと deploy ジョブを登録する
        jobs:
            - test
            - deploy:
                filters:
                    branches:
                        only: main #テスト用.動いたらmain(productionに向ける)