version:  2.1
jobs:
  build:
    docker:
    #使用するdockerイメージ
      - image: cystdot/ubuntu:circleci
        auth:
          username: cystdot
          password: senuma211

    working_directory: ~/workspace/spring-demo-gradle
    #処理内容
    steps:
      - run:
          TAG=0.1.$CIRCLE_BUILD_NUM
          docker build -t cystdot/ubuntu:circleci .
          echo senuma211 | docker login -u cystdot --password-stdin
          docker push cystdot/ubuntu:circleci

#workflowでテスト通ったらビルドとか設定できる??
#流れ...prの内容を含むDocker imageをビルド→そのイメージを元にコンテナ起動→その内容を含むテスト実行→テスト通ったらOK