version:  2.1
jobs:
  build:
    docker:
    #使用するdockerイメージ
      - image: cystdot/ubuntu:latest
    working_directory: ~/workspace/spring-demo-gradle
    #処理内容
    steps:
      - run: echo "my ubuntu image was run!!"
      - run: echo "start testing..."
      - run: pwd
      - run: ls
