version:  2.1
jobs:
  build:
    docker:
    #使用するdockerイメージ
      - image: cystdot/circleci

    working_directory: ~/workspace/spring-demo-gradle

    steps:
      - run: echo enter circleci
      - run: echo this branch is to test aws