version:  2.1
jobs:
    # deploy: EC2 に SSH 接続して、デプロイを実行する
    deploy: 
        docker:
            - image: cystdot/ubuntu:ToExecSsh #imageの中に秘密鍵入ってるからprivateにしてある
              auth:
                username: ${DOCKER_USER}
                password: ${DOCKER_PASSWORD}
        steps:
            # CircleCI に登録した環境変数を使って SSH
            - run: ssh -i /.ssh/aws-network-test-key-latest.pem ${SSH_USER}@${SSH_HOST} 'sh deploy-me.sh'

    test:
        docker:
          - image: cimg/openjdk:11.0.12 #テスト用イメージ

        working_directory: ~/spring-demo-gradle

        environment:
          # Customize the JVM maximum heap limit
          JVM_OPTS: -Xmx3200m
          TERM: dumb

        steps:
           - checkout

           - restore_cache:
               keys:
               - v1-dependencies-{{ checksum "build.gradle" }}
               - v1-dependencies-

           - run: gradle dependencies

           - save_cache:
               paths:
                  - ~/.gradle
               key: v1-dependencies-{{ checksum "build.gradle" }}

           - run: gradle test

workflows:
    version: 2
    # test_and_deploy ジョブ:テストは常時行い、デプロイはmainに向けられたときのみ行う
    test_and_deploy:
        # test ジョブと deploy ジョブを登録する
        jobs:
            - test
            - deploy:
                filters: 
                    branches:
                        only: main #デプロイするのはmainブランチにプッシュされたときのみ