version:  2.1
jobs:
  build:
    docker:
    #使用するdockerイメージ
      - image: cystdot/ubuntu:circleci
    working_directory: ~/workspace/spring-demo-gradle
    #処理内容
    steps:
      - run: echo "my ubuntu image was run!!"
      - run: echo "start testing..."
      - run: pwd
      - run: ls
      - run: echo "test"
      - run: echo "aaa"

#workflowでテスト通ったらビルドとか設定できる??
#流れ...prの内容を含むDocker imageをビルド→そのイメージを元にコンテナ起動→その内容を含むテスト実行→テスト通ったらOK